<?php

namespace ContainerNdOxlXx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApplicationService extends NapoleonCat_KernelDevContainer
{
    /*
     * Gets the public 'Symfony\Component\Console\Application' shared autowired service.
     *
     * @return \Symfony\Component\Console\Application
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Symfony\\Component\\Console\\Application'] = new \Symfony\Component\Console\Application();
    }
}
