# config/services.yml
services:
  _defaults:
    autowire: true
    bind:
      $appId: '%env(APP_ID_ENV_NAME)%'
      $appSecret: '%env(APP_SECRET_ENV_NAME)%'
      $appToken: '%env(LONG_TIME_TOKEN)%'

  NapoleonCat\:
    resource: '../src'

  Symfony\Component\Console\Application:
    public: true
  Facebook\Facebook:
    public: true