<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXWc0YI2\NapoleonCat_KernelContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXWc0YI2/NapoleonCat_KernelContainer.php') {
    touch(__DIR__.'/ContainerXWc0YI2.legacy');

    return;
}

if (!\class_exists(NapoleonCat_KernelContainer::class, false)) {
    \class_alias(\ContainerXWc0YI2\NapoleonCat_KernelContainer::class, NapoleonCat_KernelContainer::class, false);
}

return new \ContainerXWc0YI2\NapoleonCat_KernelContainer([
    'container.build_hash' => 'XWc0YI2',
    'container.build_id' => '3a7b48f4',
    'container.build_time' => 1618262526,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXWc0YI2');
