<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNB6ZmDg\NapoleonCat_KernelContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNB6ZmDg/NapoleonCat_KernelContainer.php') {
    touch(__DIR__.'/ContainerNB6ZmDg.legacy');

    return;
}

if (!\class_exists(NapoleonCat_KernelContainer::class, false)) {
    \class_alias(\ContainerNB6ZmDg\NapoleonCat_KernelContainer::class, NapoleonCat_KernelContainer::class, false);
}

return new \ContainerNB6ZmDg\NapoleonCat_KernelContainer([
    'container.build_hash' => 'NB6ZmDg',
    'container.build_id' => '827cc3e1',
    'container.build_time' => 1618140924,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNB6ZmDg');
