<?php

// This file has been auto-generated by the Symfony Dependency Injection Component
// You can reference it in the "opcache.preload" php.ini setting on PHP >= 7.4 when preloading is desired

use Symfony\Component\DependencyInjection\Dumper\Preloader;

if (in_array(PHP_SAPI, ['cli', 'phpdbg'], true)) {
    return;
}

require 'E:\\napoleoncat-recruitment\\vendor/autoload.php';
require __DIR__.'/ContainerNB6ZmDg/NapoleonCat_KernelContainer.php';
require __DIR__.'/ContainerNB6ZmDg/getApplicationService.php';

$classes = [];
$classes[] = 'Symfony\Component\Console\Application';
$classes[] = 'NapoleonCat\Command\FeedScanner';
$classes[] = 'NapoleonCat\Services\PageScanner';
$classes[] = 'Symfony\Component\DependencyInjection\ContainerInterface';

Preloader::preload($classes);
