<?php

namespace ContainerXWc0YI2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApplicationService extends NapoleonCat_KernelContainer
{
    /*
     * Gets the public 'Symfony\Component\Console\Application' shared autowired service.
     *
     * @return \Symfony\Component\Console\Application
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['Symfony\\Component\\Console\\Application'] = $instance = new \Symfony\Component\Console\Application();

        $a = new \NapoleonCat\Integrations\Facebook\FacebookApi($container->getEnv('APP_ID_ENV_NAME'), $container->getEnv('APP_SECRET_ENV_NAME'), $container->getEnv('LONG_TIME_TOKEN'));

        $instance->add(new \NapoleonCat\Command\FeedScanner(new \NapoleonCat\Services\PageScanner(new \NapoleonCat\Integrations\Facebook\FacebookService(new \NapoleonCat\Integrations\Facebook\Posts\PostsService($a), new \NapoleonCat\Integrations\Facebook\Comments\CommentService($a))), $container->getEnv('APP_ID_ENV_NAME')));

        return $instance;
    }
}
