<?php

namespace ContainerXWc0YI2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFacebookService extends NapoleonCat_KernelContainer
{
    /*
     * Gets the public 'Facebook\Facebook' shared autowired service.
     *
     * @return \Facebook\Facebook
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Facebook\\Facebook'] = new \Facebook\Facebook();
    }
}
