<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNdOxlXx\NapoleonCat_KernelDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNdOxlXx/NapoleonCat_KernelDevContainer.php') {
    touch(__DIR__.'/ContainerNdOxlXx.legacy');

    return;
}

if (!\class_exists(NapoleonCat_KernelDevContainer::class, false)) {
    \class_alias(\ContainerNdOxlXx\NapoleonCat_KernelDevContainer::class, NapoleonCat_KernelDevContainer::class, false);
}

return new \ContainerNdOxlXx\NapoleonCat_KernelDevContainer([
    'container.build_hash' => 'NdOxlXx',
    'container.build_id' => '99c2b670',
    'container.build_time' => 1618140212,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNdOxlXx');
